"""Embed the brand fonts in a self-contained page, subset to what it uses.

    python3 brand/tools/embed_fonts.py brand/explainer/index.html [more pages]

Finds `<style id="stretto-fonts">...</style>` in each page and replaces its
content with @font-face rules whose sources are data URIs: Inter (variable,
weights 100-900, optical sizes 14-32) and JetBrains Mono (Regular and Bold),
each cut down to the characters that appear anywhere in the page, plus
printable ASCII. Run it again after editing a page's text. The fonts are
brand/fonts/*.subset.woff2, under the SIL Open Font License 1.1.
"""

import base64
import io
import re
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

FONTS = Path(__file__).resolve().parent.parent / "fonts"
BLOCK = re.compile(r'(<style id="stretto-fonts">)(.*?)(</style>)', re.S)
FEATURES = ["kern", "liga", "calt", "ccmp", "locl", "mark", "mkmk", "case", "tnum", "lnum", "pnum"]


def cut(path: Path, text: str) -> str:
    # Keep the head table's modified date, so the same page embeds to the same bytes.
    font = TTFont(path, recalcTimestamp=False)
    options = subset.Options()
    options.layout_features = FEATURES
    options.flavor = "woff2"
    options.name_IDs = ["*"]
    options.notdef_outline = True
    sub = subset.Subsetter(options)
    cmap = font.getBestCmap()
    chars = {ord(c) for c in text} | set(range(0x20, 0x7F))
    sub.populate(unicodes=[c for c in chars if c in cmap])
    sub.subset(font)
    font.flavor = "woff2"
    out = io.BytesIO()
    font.save(out)
    return base64.b64encode(out.getvalue()).decode("ascii")


def embed(page: Path) -> None:
    html = page.read_text()
    if not BLOCK.search(html):
        sys.exit(f"{page}: no <style id=\"stretto-fonts\"> block")
    text = BLOCK.sub(r"\1\3", html)
    rules = [
        "/* Generated by brand/tools/embed_fonts.py: Inter and JetBrains Mono (SIL OFL 1.1),"
        " subset to this page's characters. */",
        '@font-face{font-family:"Inter";font-style:normal;font-weight:100 900;font-display:swap;'
        f'src:url(data:font/woff2;base64,{cut(FONTS / "Inter-Variable.subset.woff2", text)}) format("woff2")}}',
    ]
    for weight, name in ((400, "Regular"), (700, "Bold")):
        rules.append(
            f'@font-face{{font-family:"JetBrains Mono";font-style:normal;font-weight:{weight};font-display:swap;'
            f'src:url(data:font/woff2;base64,{cut(FONTS / f"JetBrainsMono-{name}.subset.woff2", text)}) format("woff2")}}'
        )
    html = BLOCK.sub(lambda m: m.group(1) + "\n" + "\n".join(rules) + "\n" + m.group(3), html, count=1)
    page.write_text(html)
    print(f"{page}: {page.stat().st_size / 1024:.1f} KiB")


if __name__ == "__main__":
    for arg in sys.argv[1:]:
        embed(Path(arg))
